[package]
name = "december_twentytwo"
version = "0.1.0"
authors = ["nouman-96 <noumanqadri786@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
